# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'TFAtWar' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks! :linkage => :static

  pod 'TFCommonKit', :path => "../Libs/TFCommonKit", :preserve_pod_file_structure => true
  pod 'TFData', :path => "../Libs/TFData", :preserve_pod_file_structure => true
  pod 'TFiOSKit', :path => "../Libs/TFiOSKit", :preserve_pod_file_structure => true
  pod 'TFWarEngine', :path => "../Libs/TFWarEngine", :preserve_pod_file_structure => true, :testspecs => ['TFWarEngineTests'] 

  # Pods for TFAtWar

  target 'TFAtWarTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TFAtWarUITests' do
    # Pods for testing
  end

end
