use_frameworks! :linkage => :static

platform :ios, '10.0'

target 'TFWarEngine_Example' do
  pod 'TFWarEngine', :path => '../'
  
  pod 'TFData', :path => '../../TFData/'

  target 'TFWarEngine_Tests' do
    inherit! :search_paths

    
  end
end
